### ISSUE TITLE
NewHashedTimeWheel not exist

### ISSUE THREAD

**Issue by coseyo** [fagongzi/goetty#2]
NewHashedTimeWheel func is not exist?

**Comment by zhangxu19830126** [comment]
The lastest commit is change timer wheel implemention, use goetty.NewTimeoutWheel to instead

**Comment by zhangxu19830126** [comment]
if you are use goetty pkg, please use vendor or godep to manager your dependences

**Comment by coseyo** [comment]
after change to NewTimeoutWheel,then err below

`$ go build cmd/proxy/proxy.go
# github.com/fagongzi/gateway/pkg/model
pkg\model\ruletable.go:95: cannot use time.Second (type time.Duration) as type goetty.Option in argument to goetty.NewTimeoutWheel
pkg\model\ruletable.go:95: cannot use 60 (type int) as type goetty.Option in argument to goetty.NewTimeoutWheel
pkg\model\ruletable.go:95: cannot use 3 (type int) as type goetty.Option in argument to goetty.NewTimeoutWheel
pkg\model\ruletable.go:513: undefined: goetty.HashedTimeWheel
pkg\model\ruletable.go:711: r.tw.Cancel undefined (type *goetty.TimeoutWheel has no field or method Cancel)
pkg\model\ruletable.go:732: r.tw.AddWithID undefined (type *goetty.TimeoutWheel has no field or method AddWithID)`

I think the gateway and goetty should both have a stable version to use. otherwise, you can mark something to tell other about this staff. It would help a lot. Thanks for replay!

**Comment by zhangxu19830126** [comment]
The fagongzi/gateway project has its's own goetty pkg under the vendor folder. Are you put the gateway project under the $GOPATH/src/github.com/fagongzi/gateway folder?

**Comment by zhangxu19830126** [comment]
I found the gateway project's vendor  folder are not contains the goetty pkg, it's a bug.

**Comment by coseyo** [comment]
Year, Just wanna say that~

**Comment by zhangxu19830126** [comment]
fixed
